name: CI
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Bump version
        run: |
          git config user.name "Fookie Bot"
          git config user.email "admin@fookiejs.com"
          npm version patch

      - name: Install dependencies
        run: npm ci

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push new version
        run: git push
